### ISSUE TITLE
How can i use module flask_select2

### ISSUE THREAD

**Issue by LukasSliacky** [pjcunningham/Flask-Select2#1]
Hello Paul, 

thank you for your example.
Sorry, but i cann't how to use module flask_select2. Where can i find module for this imports?

`
from flask_select2 import Select2
`
`
from flask_select2.model.fields import AjaxSelectField, AjaxSelectMultipleField
`

Thank you.
Lukas

**Comment by LukasSliacky** [comment]
Okay, I had to copy folder "flask_select2" to folder "basic". 
Now it works fine...

**Comment by pjcunningham** [comment]
Hello Lukas,

Glad you sorted it out. The intention is to make the project installable via PIP - when I get the time!

Cheers, Paul.

**Comment by LukasSliacky** [comment]
That will be great :)
Thank you.
